version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
      - aws s3 cp tenant-management/target/tenant-management-1.0-SNAPSHOT.jar s3://cloud-idp-bucket/lcip-lambdas/tenant-management-1.0-SNAPSHOT.jar
      - aws s3 cp token-generator/target/token-generator-1.0-SNAPSHOT.jar s3://cloud-idp-bucket/lcip-lambdas/token-generator-1.0-SNAPSHOT.jar
      - aws s3 cp token-validator/target/token-validator-1.0-SNAPSHOT.jar s3://cloud-idp-bucket/lcip-lambdas/token-validator-1.0-SNAPSHOT.jar
      - aws s3 cp app-management/target/app-management-1.0-SNAPSHOT.jar s3://cloud-idp-bucket/lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws s3 cp user-management/target/user-management-1.0-SNAPSHOT.jar s3://cloud-idp-bucket/lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - echo Uploaded Jar to S3 location successfully
      - aws lambda update-function-code --function-name getUserDetails --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name userRegistration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name listAllUsers --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name userDeletion --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name appList --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name appRegistration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name applicationDeletion --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name getApplicationDetails --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name listAllTenants --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/tenant-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name getTenantDetails --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/tenant-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name deleteTenant --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/tenant-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name tenantRegistration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/tenant-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name tokenGeneration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/token-generator-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name ValidatorLambda --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/token-validator-1.0-SNAPSHOT.jar
      - echo Lambda deployment completed successfully
