version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
      - aws lambda update-function-code --function-name getUserDetails --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name userRegistration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name listAllUsers --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name userDeletion --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name appList --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name appRegistration --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name applicationDeletion --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - aws lambda update-function-code --function-name getApplicationDetails --region us-east-1 --s3-bucket cloud-idp-bucket --s3-key lcip-lambdas/app-management-1.0-SNAPSHOT.jar
      - echo Lambda deployment completed successfully
artifacts:
  files:
    - user-management/target/user-management-1.0-SNAPSHOT.jar
    - app-management/target/app-management-1.0-SNAPSHOT.jar
    - tenant-management/target/tenant-management-1.0-SNAPSHOT.jar
    - token-generator/target/token-generator-1.0-SNAPSHOT.jar
  discard-paths: yes
