version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
      - aws lambda update-function-code --function-name getUserDetails --region us-east-1 --s3-bucket s3://cloud-idp-bucket/lcip-lambdas/user-management-1.0-SNAPSHOT.jar
      - echo Lambda deployment completed successfully
artifacts:
  files:
    - user-management/target/user-management-1.0-SNAPSHOT.jar
    - app-management/target/app-management-1.0-SNAPSHOT.jar
    - tenant-management/target/tenant-management-1.0-SNAPSHOT.jar
    - token-generator/target/token-generator-1.0-SNAPSHOT.jar
  discard-paths: yes
